version: "3.9"
    
services:
  mailhog:
      image: mailhog/mailhog
      # logging:
      #   driver: none  # disable saving logs to prevent bloat
      ports:
        - 127.0.0.1:8025:8025 # web ui

  db:
    image: mysql:5.7
    volumes:
      - ./docker/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wp
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
    
  wordpress:
    depends_on:
      - db
      - mailhog
    build: .
    volumes:
      - ./wp-plugins/plugins:/var/www/html/wp-content/plugins
      - ./wp-themes/themes:/var/www/html/wp-content/themes
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80